[package]
name = "movs"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.9"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
walkdir = "2.5.0"
thiserror = "2.0.17"
chrono = { version = "0.4.42", features = ["serde"] }
rayon = "1.11.0"
hex = "0.4.3"